---
backup:
  provider: aws
  type: t2.micro
  subnet: subnet-2bf1304e
  image: ami-6c14310f
  tags:
    Environment: Env1
    Name: backup
  volumes:
    /dev/sda: 20

ns1:
  provider: gcp
  type: f1-micro
  subnet: somesubnet
  ip: 10.10.10.2
  image: someimage
  tags:
    Environment: DMZ
    Name: ns1
